/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AiCopilotRouteImport } from './routes/ai-copilot'
import { Route as IndexRouteImport } from './routes/index'

const AiCopilotRoute = AiCopilotRouteImport.update({
  id: '/ai-copilot',
  path: '/ai-copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-copilot': typeof AiCopilotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-copilot': typeof AiCopilotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-copilot': typeof AiCopilotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ai-copilot'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ai-copilot'
  id: '__root__' | '/' | '/ai-copilot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiCopilotRoute: typeof AiCopilotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ai-copilot': {
      id: '/ai-copilot'
      path: '/ai-copilot'
      fullPath: '/ai-copilot'
      preLoaderRoute: typeof AiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiCopilotRoute: AiCopilotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
